### ISSUE TITLE
1.8 custom types support

### ISSUE THREAD

**Issue by lockie** [Zulu-Inuoe/cl-tiled#29]
Hey! Thanks for awesome library, it has been addressing my Tiled loading needs perfectly :)

I have a question, would that be too hard to support [custom types](https://doc.mapeditor.org/en/stable/manual/custom-properties/#custom-types) that has been added to Tiled 1.8? It would be ideal for tight integration with custom engines.

**Comment by Zulu-Inuoe** [comment]
Hey, thanks for asking. I'll have to give it a more thorough peek, but I think we could expose something basic out which does basic validation, if I am understanding the feature correctly.
I haven't been programming in my spare time much lately, so I don't know that I'd get to it any time soon myself.

I'd be happy to help where I can, and take PR's in, though!.
