### ISSUE TITLE
Map from relative path with external files

### ISSUE THREAD

**Issue by lockie** [Zulu-Inuoe/cl-tiled#34]
Hello @Zulu-Inuoe!
There's currently minor inconvenience using the library, namely using relative paths for map. When there are references to external files (e.g. tilesets), `load-map` should be called with full absoulte path. That's perfectly reasonable, however it's not viable when using nontrivial file loading code. Consider liballegro library which uses [PhysFS](https://icculus.org/physfs) library to be able to load files from ZIP archives, Quake PAK files, Doom WADs and other types of game archives; here's the example (it needs [this](https://github.com/mapeditor/tiled/archive/refs/heads/master.zip) ZIP file alongside it):

```lisp
(ql:quickload '(:cl-tiled :cl-liballegro))

(cffi:defcfun ("PHYSFS_init" physfs-init) :int (argv0 :string))
(cffi:defcfun ("PHYSFS_getLastError" physfs-get-last-error) :string)
(cffi:defcfun ("PHYSFS_mount" physfs-mount) :int
  (new-dir :string) (mount-point :string) (append-to-path :int))

(when (zerop (physfs-init (first (uiop/image:raw-command-line-arguments))))
  (error "Failed to init PhysFS: ~a" (physfs-get-last-error)))

(al:set-physfs-file-interface)

;; download from https://github.com/mapeditor/tiled/archive/refs/heads/master.zip
(when (zerop (physfs-mount "tiled-master.zip" (cffi:null-pointer) 0))
  (error "Failed to mount tiled-master.zip: ~a" (physfs-get-last-error)))

;; reading from ZIP file works
(print
 (alexandria:read-stream-content-into-string
  (al:make-character-stream "tiled-master/examples/desert.tmx")))

;; this currently does not
(cl-tiled:load-map "tiled-master/examples/desert.tmx"
                   (lambda (path &rest rest)
                     (declare (ignore rest))
                     (alexandria:read-stream-content-into-string
                      (al:make-character-stream path))))

```

As you can see, `cl-tiled:parse-xml-map-stream` erroneously tries to `chdir` to `tiled-master/examples`, while this directory exists only within ZIP archive.

My question is, would you be willing to accept a pull request remedying this paths situation?

**Comment by Zulu-Inuoe** [comment]
Yes, this is something I had in mind originally when writing this lib, hence why you can pass a custom reader to `load-map` for dependencies. The current implementation changing directories like that is a design oversight of not figuring it out as well as I should have. So, fully open to improvements there

**Comment by lockie** [comment]
Awesome, I'll implement the changes in nearest future.
