### ISSUE TITLE
value NIL is not of type CL-TILED.DATA-TYPES:TILED-TILE when load-map

### ISSUE THREAD

**Issue by bymoz089** [Zulu-Inuoe/cl-tiled#37]
### Description
Loading of various tmx and tsx files leads to trap into debugger.

### reproducing
With the minimal example code from the Readme file, I tried to load different maps and tilesets. For example [this resources](https://github.com/vocksel/react-pixi-tilemap/tree/master/demo/public/stages).

    [... same example code as in README, but following ]
    
    (let ((tiled-map (tiled:load-map "map.tmx")))  ;; files from above mentioned resources link
      (dolist (layer (tiled:map-layers tiled-map))
        (render-layer layer)))

Tried with sbcl 2.4.8 and current version of this system.

### expected behavior
loading of tileset succeeds.

### observed (buggy) behavior
sbcl throws me into the debugger, which states

> The value
>   NIL
> is not of type
>   CL-TILED.DATA-TYPES:TILED-TILE

### observed problematic code
    file: data-types.lisp
    class definition: of tile-object
    slot: tile
    slot-parameter: :type
    slot-parameter-value: tiled-tile

### proposed fix

change slot-parameter-value from `tiled-tile` to `(or null tiled-tile)`

so the class definition would change from:

    (defclass tile-object (object)
      ((tile
        :documentation "The tile used by this object."
        :type tiled-tile
        :initarg :tile
        :reader object-tile)
       (width
        [...]

to:

    (defclass tile-object (object)
      ((tile
        :documentation "The tile used by this object."
        :type (or null tiled-tile)
        :initarg :tile
        :reader object-tile)
       (width
        [...]

**Comment by Zulu-Inuoe** [comment]
Hi! Thanks for the report. Looks like you're not the only one affected - seems this is fixed by #38
