### ISSUE TITLE
XML Object Properties with newlines not being loaded

### ISSUE THREAD

**Issue by Zulu-Inuoe** [Zulu-Inuoe/cl-tiled#4]
From https://github.com/Zulu-Inuoe/cl-tiled/pull/3#issuecomment-434606812

XML Object properties are usually stored as attributes:
```xml
<properties>
  <property name="text" value="Foo"/>
</properties>
```

But when the value contains a newline it is saved as the text value for the xml node as:

```xml
<properties>
  <property name="text">Foobar
baz
qux</property>
</properties>
```

cl-tiled doesn't handle the latter.

**Comment by Zulu-Inuoe** [comment]
Fixed in ed070917c4dd3fba3b1e4871de2584ad5d9820c0

**Comment by defaultxr** [comment]
Thank you!! (And for the library in general, it's been very helpful for me) :)

**Comment by Zulu-Inuoe** [comment]
I'm really happy to hear it! Thanks for checking it out!
